### ISSUE TITLE
error when registering in latest main

### ISSUE THREAD

**Issue by kurokirasama** [fdncred/nu_plugin_pnet#1]
I just updated nushell to latest main and I got this error when trying to register:
```bash
registering /home/kira/.cargo/bin/nu_plugin_pnet...
Error: 
  × Error getting signatures
   ╭─[source:1:1]
 1 │ register /home/kira/.cargo/bin/nu_plugin_pnet
   · ────┬───
   ·     ╰── Plugin failed to decode: invalid type: string "Experimental", expected a boolean
```

**Comment by fdncred** [comment]
I ran into this yesterday. The key to remember with plugins, that I also forgot yesterday, is that it's super important that plugins and nushell be on the precisely exact same version. When I got this problem yesterday I was compiling with plugins 0.73.0 against nushell 0.73.1 which will not work and gave me this same error message. So, I pointed my plugins to my nushell repo and that fixed it for me.

**Comment by kurokirasama** [comment]
cool! How do I do that pointer thing?

**Comment by fdncred** [comment]
You have to change the cargo.toml. I updated my repo but you'll have to have nushell cloned so that it and plugins are at the same level.
./nushell
./nu_plugin_1
./nu_plugin_1

**Comment by kurokirasama** [comment]
ok, thanks!
