### ISSUE TITLE
failed to get `nu-plugin` as a dependency of package `nu_plugin_pnet v1.2.0`

### ISSUE THREAD

**Issue by amtoine** [fdncred/nu_plugin_pnet#2]
hello there :yum: :wave: 

i tried to install this plugin, originally `net`, to see what plugins can do :relieved: 
however, i'm having some trouble...

**are we supposed to clone this repo and build it from source from there?** :thinking: 

from inside the root of this repo, all of the commands below
- `cargo build`
- `cargo run`
- `cargo install --path .`

give the following error
```bash
error: failed to get `nu-plugin` as a dependency of package `nu_plugin_pnet v1.2.0 (/home/amtoine/.local/share/ghq/github.com/fdncred/nu_plugin_pnet)`

Caused by:
  failed to load source for dependency `nu-plugin`

Caused by:
  Unable to update /home/amtoine/.local/share/ghq/github.com/fdncred/nushell/crates/nu-plugin

Caused by:
  failed to read `/home/amtoine/.local/share/ghq/github.com/fdncred/nushell/crates/nu-plugin/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**i'm probably missing something obvious...** but i'm quite confused :open_mouth: 

see ya :wave: :wink:

**Comment by fdncred** [comment]
Yes, since my plugins are not published, and I try to keep them kind of up to date, it requires that you clone the repo.  You can see this by looking at how the Cargo.toml references the nu crates. They're like this so you can easily change it to 0.74.1 or whatever the latest version is and recompile.

https://github.com/fdncred/nu_plugin_pnet/blob/8f22aa54a100e373d20ffb2aef795b8edf57c22d/Cargo.toml#L15-L16

**Comment by amtoine** [comment]
> Yes, since my plugins are not published, and I try to keep them kind of up to date, it requires that you clone the repo. You can see this by looking at how the Cargo.toml references the nu crates. They're like this so you can easily change it to 0.74.1 or whatever the latest version is and recompile.
> 
> https://github.com/fdncred/nu_plugin_pnet/blob/8f22aa54a100e373d20ffb2aef795b8edf57c22d/Cargo.toml#L15-L16
>
the paths to the crates are hardcoded in `Cargo.toml`!!

we do not have the same architecture of repo i think :relieved: 

i'll try and keep you up-to-date about whether i make it or not :wave:

**Comment by fdncred** [comment]
ya, i'm doing something that shouldn't be done, but there aren't very good ways to keep crates up to date like this. For instance, if i published it for every version, I wouldn't be able to use it because after every version we make a dev version. So like 0.74.0 is published and then we go to 0.74.1. If the plugin is on 0.74.0 and my main branch is on 0.74.1, I usually can't compile it and get errors.

**Comment by amtoine** [comment]
> ya, i'm doing something that shouldn't be done, but there aren't very good ways to keep crates up to date like this. For instance, if i published it for every version, I wouldn't be able to use it because after every version we make a dev version. So like 0.74.0 is published and then we go to 0.74.1. If the plugin is on 0.74.0 and my main branch is on 0.74.1, I usually can't compile it and get errors.
>
so you'd need to republish a `0.74.1` for `nu_plugin_pnet`? :thinking:

**Comment by amtoine** [comment]
ok, i was able to install the plugin with
```diff
diff --git a/Cargo.toml b/Cargo.toml
index d4cc51a..5dd19f7 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -12,7 +12,7 @@ readme = "README.md"
 
 [dependencies]
 pnet = { version = "0.31", features = ["std"] }
-nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.73.1" }
-nu-protocol = { path = "../nushell/crates/nu-protocol", version = "0.73.1", features = [
+nu-plugin = { path = "../../nushell/nushell/crates/nu-plugin", version = "0.74.1" }
+nu-protocol = { path = "../../nushell/nushell/crates/nu-protocol", version = "0.74.1", features = [
     "plugin",
 ] }
```
then
```bash
register ~/.local/share/cargo/bin/nu_plugin_pnet
```
and finally
```bash
> pnet
╭───┬────────┬─────────────┬──────────┬─────┬────────────────┬───────────────────╮
│ # │  name  │ description │ if_index │ mac │      ips       │       flags       │
├───┼────────┼─────────────┼──────────┼─────┼────────────────┼───────────────────┤
│ 0 │ lo     │             │        1 │ ... │ [table 2 rows] │ {record 5 fields} │
│ 1 │ wlp2s0 │             │        2 │ ... │ [table 3 rows] │ {record 5 fields} │
╰───┴────────┴─────────────┴──────────┴─────┴────────────────┴───────────────────╯
```

## great :ok_hand:

**Comment by fdncred** [comment]
yup, that's exactly right.
